@Base = http://localhost:4200/api/messages

### Get all
GET {{Base}}

### Get by id
GET {{Base}}/019c6cf4-3752-7fb5-845c-2973dcd2391f

### Create
POST {{Base}}
Content-Type: application/json

{
  "text": "Message #2"
}

### Update
PUT {{Base}}/019c6cf4-3752-7fb5-845c-2973dcd2391f
Content-Type: application/json

{
  "text": "updated message"
}

### Delete
DELETE {{Base}}/019c6cf4-3752-7fb5-845c-2973dcd2391f